<div id="svp-main-sidebar" class="uk-width-1-3@m">
    <div uk-sticky="end: true; offset: 90; media: 980">
        
        <div class="uk-margin uk-card uk-card-body uk-border-rounded uk-overflow-hidden uk-background-default">
            <div class="fb-page fb_iframe_widget" data-href="https://www.facebook.com/svp.ge/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="adapt_container_width=true&app_id=2305689746356218&container_width=307&hide_cover=false&href=https%3A%2F%2Fwww.facebook.com%2Fsvp.ge%2F&locale=en_GB&sdk=joey&show_facepile=true&small_header=false"><span style="vertical-align: bottom; width: 307px; height: 130px;"><iframe name="f3e486b984f6da" data-testid="fb:page Facebook Social Plugin" title="fb:page Facebook Social Plugin" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v3.3/plugins/page.php?adapt_container_width=true&app_id=2305689746356218&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df342e8a7975d72c%26domain%3Dsvp.ge%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Fsvp.ge%252Ff363097e074ded4%26relation%3Dparent.parent&container_width=307&hide_cover=false&href=https%3A%2F%2Fwww.facebook.com%2Fsvp.ge%2F&locale=en_GB&sdk=joey&show_facepile=true&small_header=false" style="border: none; visibility: visible; width: 307px; height: 130px;" class="" width="1000px" height="1000px" frameborder="0"></iframe></span></div>
        </div>

        <div class="uk-margin uk-card uk-card-body uk-border-rounded uk-overflow-hidden uk-background-default">
            <div class="fb-group fb_iframe_widget fb_iframe_widget_fluid" data-href="https://www.facebook.com/groups/svp.ge/" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=2305689746356218&container_width=307&href=https%3A%2F%2Fwww.facebook.com%2Fgroups%2Fsvp.ge%2F&locale=en_GB&sdk=joey&show_metadata=true&show_social_context=true&width=307" data-show-metadata="true" data-show-social-context="true" data-width="307"><span style="vertical-align: bottom; width: 307px; height: 360px;"><iframe name="f2c102eeeaddbec" data-testid="fb:group Facebook Social Plugin" title="fb:group Facebook Social Plugin" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v3.3/plugins/group.php?app_id=2305689746356218&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df1633f5674aed48%26domain%3Dsvp.ge%26origin%3Dhttps%253A%252F%252Fsvp.ge%252Ff8f27ac3aa511%26relation%3Dparent.parent&container_width=307&href=https%3A%2F%2Fwww.facebook.com%2Fgroups%2Fsvp.ge%2F&locale=en_GB&sdk=joey&show_metadata=true&show_social_context=true&width=307" style="border: none; visibility: visible; width: 307px; height: 360px;" class="" width="307px" height="1000px" frameborder="0"></iframe></span></div>
        </div>

        <div class="uk-margin uk-card uk-card-body uk-border-rounded uk-overflow-hidden uk-background-default">
            <div class="fb-group fb_iframe_widget fb_iframe_widget_fluid" data-href="https://www.facebook.com/groups/svp.tavisufali/" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=2305689746356218&container_width=307&href=https%3A%2F%2Fwww.facebook.com%2Fgroups%2Fsvp.tavisufali%2F&locale=en_GB&sdk=joey&show_metadata=true&show_social_context=true&width=307" data-show-metadata="true" data-show-social-context="true" data-width="307"><span style="vertical-align: bottom; width: 307px;"><iframe name="f70d60ff2bdd08" data-testid="fb:group Facebook Social Plugin" title="fb:group Facebook Social Plugin" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v3.3/plugins/group.php?app_id=2305689746356218&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df1488bcdd56f49c%26domain%3Dsvp.ge%26origin%3Dhttps%253A%252F%252Fsvp.ge%252Ff8f27ac3aa511%26relation%3Dparent.parent&container_width=307&href=https%3A%2F%2Fwww.facebook.com%2Fgroups%2Fsvp.tavisufali%2F&locale=en_GB&sdk=joey&show_metadata=true&show_social_context=true&width=307" style="border: none; visibility: visible; width: 307px; height: 355px;" class="" width="307px" height="1000px" frameborder="0"></iframe></span></div>
        </div>
    </div>
</div>
